### ISSUE TITLE
Problème de numérotation

### ISSUE THREAD

**Issue by JeremyMagnan** [FrancoisCapon/BetaMkDocsMatrixOSCP#1]
Bonjour, 

Tout d'abord, merci, le rendu est très propre.

Je voudrai désactiver la numérotation dans la table de matière, je renseigne les numéros manuellement en fonction du chapitre et de l'exercice par rapport au PDF de l'OSCP.

![image](https://user-images.githubusercontent.com/75430341/162441370-92f57a46-c206-49ee-a649-154bf1108091.png)

Autre problème pour les exercices la numérotations reste bloquer à 1 alors qu'en markdown j'inscrit bien manuellement 1. 2. 3. et que la prévisualisation markdown affiche bien 1. 2. et 3.

![image](https://user-images.githubusercontent.com/75430341/162442038-f8244675-09b7-4e3e-8ad8-877ec7de4b68.png)
 
  Edit: J'ai réussi à désactiver le numérotation automatique en renommant les fichier print.scss correspondant.

**Comment by FrancoisCapon** [comment]
@JeremyMagnan 

Bonjour Jérémy,

> Tout d'abord, merci, le rendu est très propre. 
Merci, c'est de l'HTML et du "CSS Print" dont je découvre progressivement toutes les possibilités avec WeasyPrint, en y passant un peu de temps (génération des PDFs pour visualisation du rendu) on peut obtenir un rendu "pro".

En fait ta demande concerne deux éléments techniquement différents.

**La numération du plan du rapport**

Je viens du publier une mise à jour c61a49b731b3d84205a234dcaccde7d98eacfd1d qui permet de désactiver en colonne utilisateur (soit la `30`) _toutes les numérations_ en respectant le _principe de réécriture de la matrice_ (pas d'intervention sur les autres colonnes).

Dans tout PDF structuré digne de ce nom, il y a une table des matières "interne" qui sera en principe celle utilisée par le  lecteur de votre rapport, la mise à jour permet de la "dénuméroter" aussi si besoin (`30/1091` et `30/1120`) :

![2022-04-11--12-30-01](https://user-images.githubusercontent.com/46624375/162724863-7dd388b9-4946-4f98-925d-fa69f2e38686.png)

**La numération de listes ordonnées "chargées"**

Sauf erreur de ma part, c'est une liste ordonnée ne contenant pas seulement du texte :question: 

Il faut un exemple (le contenu en Markdown) afin que je puisse trouver l'origine du problème, c'est la structure et le type du contenu qui compte, donc si tu peux me donner en réponse un exemple :
- avec des informations "non-sensibles" :wink: 
- qui n'a pas un rendu correct

je vais gagner beaucoup de temps !

**Comment by JeremyMagnan** [comment]
Pour le second point je parle en réalité juste des questions numéroté.

Exemple: 

1. Première question
réponse 1

2. Seconde question

réponse 2

3. Troisième question 
réponse 3

J'éditerai ce post ce soir pour y rajouter un exemple en image.

**Comment by FrancoisCapon** [comment]
Tu peux me faire une copier/coller dans un bloc code de l'HTML rendu par MkDocs ?

**Comment by JeremyMagnan** [comment]
Je vous fait çà dès que je suis rentré chez moi, je viens de comprendre le problème.

Il s'agit en faites des listes qui doivent commencer par 1. mais elle sont séparé par la réponse à la question ce qui fait que la seconde question est automatiquement transformer en 1. car il s'agît du début de la liste.

**Comment by FrancoisCapon** [comment]
Oui, c'est ça, solution : utiliser un  espace insécable `&nbsp;`, l'espace est affiché mais la ligne n'est pas comprise comme étant un item de liste numérotée par le parser markdown de mkdocs :

```
1.&nbsp;Question une ? 

MkDocs is a **fast**, **simple** and **downright gorgeous** static site
generator that's geared towards building project documentation. Documentation
source files are written in Markdown, and configured with a single YAML
configuration file. Start by reading the [introductory tutorial], then check the
[User Guide] for more information.

2.&nbsp;Question deux ?

MkDocs is a **fast**, **simple** and **downright gorgeous** static site
generator that's geared towards building project documentation. Documentation
source files are written in Markdown, and configured with a single YAML
configuration file. Start by reading the [introductory tutorial], then check the
[User Guide] for more information.
```

**Comment by JeremyMagnan** [comment]
Je vous confirme que cela fonctionne, merci.
